stages:
  - build
  - test
  - deploy


build:linux:64:
  stage: build
  cache:
    # keep cache across stages
    key: "$CI_BUILD_REF_NAME/linux"
    paths:
      - cache/
  variables:
    GL_BUILD: "lin64"
  before_script:
    - ./extra/gitlab/linux-before.sh
  script:
    - pkg-config --list-all | sort
    - ./extra/gitlab/linux-script.sh
    - cp build/utox uTox-linux-x64
  artifacts:
    expire_in: 1h
    untracked: true

build:linux:muslc:
  stage: build
  image: alpine-tox-xvfb
  tags:
    - alpine-tox-xvfb
  cache:
    # keep cache across stages
    key: "$CI_BUILD_REF_NAME/linux"
    paths:
      - cache/
  variables:
    GL_BUILD: "linMUSL"
  before_script:
    - apk add freetype-dev
    - apk add openal-soft-dev
    - ./extra/common/filter_audio.sh
    - ./extra/gitlab/linux-muslc-before.sh
  script:
    - ./extra/gitlab/linux-muslc-script.sh
    - cp build/utox uTox-muslc-64
    # TODO static build here
  artifacts:
    paths:
      - uTox-muslc-64
    expire_in: 1h

build:windows:64:
  stage: build
  tags:
    - mingw64
  cache:
    paths:
      - cache/
  variables:
    GL_BUILD: "win64"
  before_script:
    - ./extra/gitlab/windows-before.sh
  script:
    - ./extra/gitlab/windows-script.sh
    - cp build_win/utox.exe uTox-Win64.exe
  artifacts:
    paths:
      - uTox-Win64.exe
    expire_in: 6h

build:macos:
  stage: build
  tags:
    - osx
  cache:
    paths:
      - cache/
  script:
    - pwd
    - docker run --rm -u $(id -u):$(id -g) -v $(pwd):/workdir -e CROSS_TRIPLE=x86_64-apple-darwin arch-build ./extra/gitlab/osx-docker.sh
    - ls -la ./*
  artifacts:
    paths:
      - utox.app/
    expire_in: 6h


.test: &test
  stage: test
  cache:
    # keep cache across stages
    key: "$CI_BUILD_REF_NAME/linux"
    paths:
      - cache/
  dependencies:
    - build:linux:64

test:chatlog:
  <<: *test
  script:
    - cd build/tests/
    - ctest -VV -R test_chatlog

test:XVFB:
  stage: test
  image: alpine-tox-xvfb
  tags:
    - alpine-tox-xvfb
  cache:
    key: "$CI_BUILD_REF_NAME/linux"
    paths:
      - cache/
  dependencies:
    - build:linux:muslc
  script:
    - Xvfb :99 &
    - export DISPLAY=:99
    - apk add openal-soft-dev
    - ls -la
    - (sleep 2m && killall uTox-muslc-64) &
    - ./uTox-muslc-64 -vvvvv || true
