language: c

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - binutils-mingw-w64
      - cmake
      - cmake-data
      - gcc-mingw-w64-x86-64
      - libdbus-1-dev
      - libopenal-data
      - libopenal-dev
      - libopenal1
      - libstdc++-8-dev
      - libv4l-dev
      - mingw-w64
      - mingw-w64-common
      - mingw-w64-x86-64-dev
      - yasm

cache:
  directories:
    - $HOME/cache

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: clang
      env: BUILD=linux

    - os: linux
      compiler: x86_64-w64-mingw32-gcc
      env: BUILD=windows

git:
  depth: 1

before_script:
  - ./extra/travis/env.sh
  - ./extra/travis/${BUILD}-before.sh
  - ./extra/travis/filter_audio.sh

script:
  - ./extra/travis/${BUILD}-script.sh

notifications:
  email: false
